#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: 
url: 'http://webjeda.com'

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv' 

description: 
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: 

# Sass/SCSS
sass:
  sass_dir: 
  style: # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: 
  ignore:
    envs: 

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
